# url is the full website URL
# baseurl is the website's URL without the hostname
url: "https://keratoconuswebsite.github.io"
baseurl: ""

title: Keratoconus Awareness
description: Keratoconus is a rare genetic disorder that develops greatly during the teenage years. Do to this, I am beginning an awareness campaign for the identification of early symptoms and inform students, parents, and teachers about keratoconus.

# List of links in the navigation bar
navbar-links:
  About Keratoconus:
    - What we do: ""
    - Join us: "join"
    - Contact: "contact"
    - Code of Conduct: "CODE_OF_CONDUCT"
  News: "blog"
  People: "people"
  Projects: "projects"
  Resources: "resources"
  Events: "events"
  Funding: "funding"
  Forum: "forum"

# Change all these values or delete the ones you don't want (these appear in the footer).
# Important: you must keep the "name" parameter, everything else you can remove
author: "Andrei Da Silva"
  name: "Keratoconus Awareness Campaign"
  email: "reidasilva75@gmail.com"
  github: keratoconuswebsite.github.io
  twitter:    # eg. daattali

# Select which links to show in the footer
footer-links-active:
  github: true
  email: true
  rss: false
  facebook: false
  twitter: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
  
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: 

# Google Analytics ID
google_analytics: 

# Output options (more information on Jekyll's site)
timezone: "Eastern Standard Time"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md

gems:
  - jekyll-paginate
